language: node_js
node_js:
  - 6
before_install:
  - npm install grunt-cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
sudo: false
cache:
  directories:
    - node_modules
